### ISSUE TITLE
docker-compose -- ERROR: for rocket_mongo_1  dictionary update sequence element #0 has length 20; 2 is required

### ISSUE THREAD

**Issue by tgeek77** [RocketChat/docs#984]
This happens every time I try to deploy with docker-compose.

`# docker-compose --version
docker-compose version 1.17.0, build unknown`
`# docker --version
Docker version 17.09.1-ce, build f4ffd2511ce9`

Opensuse Leap 15

```
# docker-compose up -d mongo
Creating network "rocket_default" with the default driver
Creating rocket_mongo_1 ... 

ERROR: for rocket_mongo_1  dictionary update sequence element #0 has length 20; 2 is required

ERROR: for mongo  dictionary update sequence element #0 has length 20; 2 is required
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 455, in up
    get_deps,
  File "/usr/lib/python2.7/site-packages/compose/parallel.py", line 70, in parallel_execute
    raise error_to_reraise
ValueError: dictionary update sequence element #0 has length 20; 2 is required
```

**Comment by jiamliang** [comment]
me too
